AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  centextautotitle-tesla

Parameters:
  ApiDomainName:
    Type: String
    Default: default-api.example.com
    Description: "API domain name"
  S3BucketName:
    Type: String
    Default: default-s3-bucket.example.com
    Description: "S3 bucket name"
  DomainName:
    Type: String
    Default: default.example.com
    Description: "Domain name"
  AccountId:
    Type: String
    Default: '123456789012'
    Description: "Account Id"
  EcsImageId:
    Type: String
  SecurityGroupIds:
    Type: String
  SubnetIds:
    Type: String

Resources:

  LanguageTranslatorFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: index.handler
        Runtime: nodejs18.x
        CodeUri: ./lambda/language-translator
        Description: "Language translator function"
        Timeout: 120
        Role: !Sub arn:aws:iam::${AccountId}:role/lambda-admin-role
        Events:
          ApiEvent:
            Type: Api
            Properties:
              Path: /language-translator
              Method: post
              RestApiId: !Ref LanguageTranslatorApi

  LanguageTranslatorFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LanguageTranslatorFunction}
      RetentionInDays: 7

  LanguageTranslatorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: codedino-lang-translator-api
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  LanguageTranslatorApiBasePathMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiMappingKey: test/ai
      DomainName: !Ref ApiDomainName
      ApiId: !Ref LanguageTranslatorApi
      Stage: !Ref LanguageTranslatorApi.Stage

